packages:
  - "apps/*"
  - "packages/*"
confirmModulesPurge: false
onlyBuiltDependencies:
  - "@prisma/engines"
  - "esbuild"
  - "prisma"
  - "sharp"
allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
