import type { PrismaClient } from "@jean/db";

export type ApiDatabase = Pick<
  PrismaClient,
  | "agent"
  | "agentConnection"
  | "agentRun"
  | "agentRunEvent"
  | "agentToolCall"
  | "approval"
  | "auditLog"
  | "artifact"
  | "artifactFile"
  | "artifactFileDiff"
  | "artifactFileVersion"
  | "artifactVersion"
  | "billingWaitlistEntry"
  | "localAgentPairingCode"
  | "organization"
  | "organizationMember"
  | "organizationPolicyRuleOverride"
  | "providerCostEntry"
  | "providerExchangeRate"
  | "room"
  | "roomComment"
  | "roomParticipant"
  | "sandboxSession"
  | "task"
  | "taskEvent"
  | "transcriptSegment"
  | "user"
  | "$disconnect"
>;
